### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by crystaltype**
Circumflex_acute and circumflex_grave

### CODE REVIEW

**Comment by alexeiva** [comment]
@crystaltype 

Do you think I can move the grave in Bold further, similarly to Regular?

screen shot 2016-08-15 at 20 59 38

**Comment by crystaltype** [comment]
I think we should rather move the regular to the left so that is similar to its bold counterpart 👍

**Comment by alexeiva** [comment]
Alright, I will do this. Thank you for clarifying.

**Comment by alexeiva** [comment]
fixed

**Pull request merged**
